name: variables basics

trigger: none

variables:
  - name: one
    value: initialValue

# stages skipped

jobs:
 - job: vars
   steps:

    - script: |
        echo ${{ variables.one }} # outputs initialValue
        echo $(one)
      displayName: First variable pass
    
    - bash: echo '##vso[task.setvariable variable=one]secondValue'
      displayName: new value one
      
    - bash: echo '##vso[task.setvariable variable=two]secondValue'
      displayName: new value one
    
    # compare syntax variants
    - script: |
        echo ${{ variables.one }} # outputs initialValue
        echo ${{ variables.two }} # outputs initialValue
      displayName: Template Expression

    - script: |
        echo $(one) # outputs secondValue
        echo $(two) # outputs secondValue
      displayName: Macro Syntax

    - script: |
        runvarone: $[variables.one]
        echo $(runvarone)	 
      displayName: Runtime Syntax
