trigger:
  branches:
    include:
      - master

variables:
  provision: true
  name: somevar
  value: somevarvalue

stages:
  - stage: stageA

    jobs:
      - job: JobA
        pool:
          vmImage: "ubuntu-latest"

        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: echo 'Executing JobA'