name: variables scopes and jobs
variables:
  globalvar: current-value # this is available to all jobs
  changingvar: original-value

stages:
  - stage: Change
    jobs:
      - job: changing_job
        pool:
          vmImage: "ubuntu-20.04"
        variables:
          jobvar: value1 # this is only available in job1
        steps:
          - bash: echo $(globalvar)
            displayName: TE globalvar
          - bash: echo $(jobvar)
            displayName: TE jobvar
          - bash: echo $JOBVAR 
            displayName: script environment jobvar
          - bash: echo $(changingvar)
          - bash: |
              echo "##vso[task.setvariable variable=changingvar;]changed-in-stage-change"
            displayName: Changing Value
          - bash: echo $(changingvar)
            displayName: TE changingvar
          - bash: echo ${{ variables.changingvar }}
            displayName: TE changingvar

  - stage: Consume
    jobs:
      - job: consuming_job
        pool:
          vmImage: "ubuntu-20.04"
        variables:
          job_variable2: value2 # this is only available in job2
        steps:
          - bash: echo $(globalvar)
          - bash: echo $(job_variable2)
          - bash: echo $GLOBAL_VAR
          - bash: echo $(changingvar)
          - bash: echo ${{ variables.changingvar }}
