name: passing vars between jobs and stages

stages:
- stage: stageStaging
  displayName: Staging
  jobs: 
  - job: job_deploy_infrastructure
    displayName: Deploy Some Infrastructure
    steps:
    - bash: |
        jobval=appService$RANDOM
        echo "##vso[task.setvariable variable=outval;isOutput=true;]$jobval"
        echo "variable value is $jobval"
      name: setvartask
  - job: job_deploy_code
    displayName: Deploy Some Code
    dependsOn: ['job_deploy_infrastructure']
    variables: 
      outval: $[ dependencies.job_deploy_infrastructure.outputs['setvartask.outval'] ]
    steps: 
    - bash: |
        echo "the variable value is:" $(outval)

- stage: stageProduction
  displayName: Procuction
  jobs:
    - job: job_procuction_eval
      displayName: productionEval
      variables:
        otherstepval: $[ stageDependencies.stageStaging.job_deploy_infrastructure.outputs['setvartask.outval'] ]
      steps:
      - bash: |
          echo "the variable value from other step is:" $(otherstepval)