name: passing vars between jobs and stages

stages:
- stage: stageStaging
  displayName: Staging
  jobs: 
  - job: job_deploy_infrastructure
    displayName: Deploy Some Infrastructure
    steps:
    - bash: |
        as=appService$RANDOM
        echo "##vso[task.setvariable variable=outval;isOutput=true;]$as"
        echo "provisioned appservice $as"
      name: mockProvisioning
  - job: job_deploy_code
    displayName: Deploy Some Code
    dependsOn: ['job_deploy_infrastructure']
    variables: 
      appName: $[ dependencies.job_deploy_infrastructure.outputs['mockProvisioning.outval'] ]
    steps: 
    - bash: |
        echo "deployed code to:" $(appName)

- stage: stageProduction
  displayName: Procuction
  jobs:
    - job: job_procuction_eval
      displayName: productionEval
      variables:
        stagingApp: $[ stageDependencies.stageStaging.job_deploy_infrastructure.outputs['mockProvisioning.outval'] ]
      steps:
      - bash: |
          echo "the staging app is:" $(stagingApp)